//! Procedural macros for `gloam-commands`.

use proc_macro::TokenStream;

mod command;
mod commands;

/// Declares a Discord chat-input slash command.
#[proc_macro_attribute]
pub fn command(attribute: TokenStream, item: TokenStream) -> TokenStream {
    command::expand(attribute.into(), item.into())
        .unwrap_or_else(syn::Error::into_compile_error)
        .into()
}

/// Builds a deterministic vector of slash commands generated by [`command`].
#[proc_macro]
pub fn commands(input: TokenStream) -> TokenStream {
    commands::expand(input.into())
        .unwrap_or_else(syn::Error::into_compile_error)
        .into()
}
