//! Procedural macros for `gloam-commands`.

use proc_macro::TokenStream;

mod autocomplete;
mod check;
mod choice;
mod command;
mod commands;
mod group;

/// Declares a Discord application-command autocomplete handler.
#[proc_macro_attribute]
pub fn autocomplete(attribute: TokenStream, item: TokenStream) -> TokenStream {
    autocomplete::expand(attribute.into(), item.into())
        .unwrap_or_else(syn::Error::into_compile_error)
        .into()
}

/// Declares an asynchronous slash-command execution check.
#[proc_macro_attribute]
pub fn check(attribute: TokenStream, item: TokenStream) -> TokenStream {
    check::expand(attribute.into(), item.into())
        .unwrap_or_else(syn::Error::into_compile_error)
        .into()
}

/// Declares a typed Discord command-option choice enum.
#[proc_macro_derive(CommandChoice, attributes(choice))]
pub fn command_choice(input: TokenStream) -> TokenStream {
    choice::expand(input.into())
        .unwrap_or_else(syn::Error::into_compile_error)
        .into()
}

/// Declares a Discord chat-input slash command.
#[proc_macro_attribute]
pub fn command(attribute: TokenStream, item: TokenStream) -> TokenStream {
    command::expand(attribute.into(), item.into())
        .unwrap_or_else(syn::Error::into_compile_error)
        .into()
}

/// Declares a Discord chat-input slash-command group from an inline module.
#[proc_macro_attribute]
pub fn group(attribute: TokenStream, item: TokenStream) -> TokenStream {
    group::expand(attribute.into(), item.into())
        .unwrap_or_else(syn::Error::into_compile_error)
        .into()
}

/// Builds a deterministic vector of slash commands generated by [`command`] or [`group`].
#[proc_macro]
pub fn commands(input: TokenStream) -> TokenStream {
    commands::expand(input.into())
        .unwrap_or_else(syn::Error::into_compile_error)
        .into()
}
