[package]
name = "gloam-commands"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "A slash-command framework for Gloamwire"

[dependencies]
gloamwire.workspace = true
gloam-commands-macros.workspace = true
thiserror.workspace = true

[dev-dependencies]
trybuild = "1"

[lints]
workspace = true
